<div align="center">
  <h1>Customer Spending Score Prediction</h1>
</div>

In [1]:
#Install the packages
%pip install pandas scikit-learn

Requirement already satisfied: pandas in ./.venv/lib/python3.12/site-packages (2.3.3)
Requirement already satisfied: scikit-learn in ./.venv/lib/python3.12/site-packages (1.7.2)
Requirement already satisfied: numpy>=1.26.0 in ./.venv/lib/python3.12/site-packages (from pandas) (2.3.3)
Requirement already satisfied: python-dateutil>=2.8.2 in ./.venv/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in ./.venv/lib/python3.12/site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in ./.venv/lib/python3.12/site-packages (from pandas) (2025.2)
Requirement already satisfied: scipy>=1.8.0 in ./.venv/lib/python3.12/site-packages (from scikit-learn) (1.16.2)
Requirement already satisfied: joblib>=1.2.0 in ./.venv/lib/python3.12/site-packages (from scikit-learn) (1.5.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in ./.venv/lib/python3.12/site-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: six>=1.5 in ./.venv/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
# Read the dataset
import pandas as pd
df = pd.read_csv('./datasets/customer_data.csv')
df.head(5)

   CustomerID  Gender  Age  Annual Income (k$)  Spending Score (1-100)
0           1    Male   19                  15                      39
1           2    Male   21                  15                      81
2           3  Female   20                  16                       6
3           4  Female   23                  16                      77
4           5  Female   31                  17                      40

In [3]:
#Get the shape
df.shape

(100, 5)

In [4]:
#check for null values
df.isnull().any()

CustomerID                False
Gender                    False
Age                       False
Annual Income (k$)        False
Spending Score (1-100)    False
dtype: bool

In [5]:
df.rename(columns = {'Spending Score (1-100)':'Spending Score'},
inplace=True)
df.rename(columns={"Annual Income (k$)": 'Annual Income'},
inplace=True)

In [6]:
df.columns

Index(['CustomerID', 'Gender', 'Age', 'Annual Income', 'Spending Score'], dtype='object')

In [7]:
# Check for duplicate rows
#df.duplicated().sum()
df.duplicated(subset=['Gender', 'Age', 'Annual Income', 'Spending Score']).sum()

np.int64(1)

In [8]:
# Prepare features and label for modeling
X = df[['Gender', 'Age', 'Annual Income']]
y = df['Spending Score']

In [9]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2,
random_state=45)
X_train.shape, y_train.shape # ((160, 4), (160,))
X_test.shape, y_test.shape # ((40, 4), (40,))

((20, 3), (20,))

In [10]:
from sklearn.preprocessing import LabelEncoder
labelencoder = LabelEncoder()
X_train['Gender'] = labelencoder.fit_transform(X_train['Gender'])
X_test['Gender'] = labelencoder.fit_transform(X_test['Gender'])

X_train.head()

    Gender  Age  Annual Income
45       0   24             39
9        0   30             19
20       1   35             24
18       0   52             23
73       0   60             50

#### Trying with Support Vector Regression Model

In [11]:
from sklearn import svm
svm_model = svm.SVR()
svm_model.fit(X_train, y_train)
svm_prediction = svm_model.predict(X_test)
from sklearn.metrics import mean_absolute_error
svm_mae = mean_absolute_error(y_test, svm_prediction)
svm_mae # 15 (Not Good!)

15.128401099936145

#### Let's try Decision Tree Regressor Model.

In [12]:
from sklearn.tree import DecisionTreeRegressor
dt_model = DecisionTreeRegressor()
dt_model.fit(X_train, y_train)
dt_prediction = dt_model.predict(X_test)
dt_mae = mean_absolute_error(y_test, dt_prediction)
dt_mae

16.0

In [13]:
from sklearn.preprocessing import StandardScaler
std_scaler = StandardScaler()
scaled_X_train = pd.DataFrame(std_scaler.fit_transform(X_train),
columns=X_train.columns, index=X_train.index)
scaled_X_test = pd.DataFrame(std_scaler.fit_transform(X_test),
columns=X_test.columns, index=X_test.index)

In [14]:
labelencoder = LabelEncoder()
scaled_X_train['Gender'] = labelencoder.fit_transform(X_train['Gender'])
scaled_X_test['Gender'] = labelencoder.fit_transform(X_test['Gender'])
svm_model.fit(scaled_X_train, y_train)
new_svm_prediction = svm_model.predict(scaled_X_test)
mean_absolute_error(y_test, new_svm_prediction)

14.855419218738096

#### let's try Linear Regression Model.

In [15]:
from sklearn.linear_model import LinearRegression
lr_model = LinearRegression()
lr_model.fit(scaled_X_train, y_train)
lr_prediction = lr_model.predict(scaled_X_test)
lr_prediction
lr_mae = mean_absolute_error(y_test, lr_prediction)
lr_mae

18.324262310771996