
<div align="center">
  <h1>Students Performance Prediction</h1>
</div>

In [3]:
import pandas as p

In [11]:
import pandas as p
df = p.read_csv("Student_Performance.csv")

In [12]:
df.head()

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index
0,7,99,Yes,9,1,91.0
1,4,82,No,4,2,65.0
2,8,51,Yes,7,2,45.0
3,5,52,Yes,5,2,36.0
4,7,75,No,8,5,66.0

In [13]:
df.isnull().sum()

Hours Studied                       0
Previous Scores                     0
Extracurricular Activities          0
Sleep Hours                         0
Sample Question Papers Practiced    0
Performance Index                   0
dtype: int64

In [14]:
df.shape # (10000, 6)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 6 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Hours Studied                     10000 non-null  int64
 1   Previous Scores                   10000 non-null  int64
 2   Extracurricular Activities        10000 non-null  object
 3   Sleep Hours                       10000 non-null  int64
 4   Sample Question Papers Practiced  10000 non-null  int64
 5   Performance Index                 10000 non-null  float64
dtypes: float64(1), int64(4), object(1)
memory usage: 468.9+ KB

In [15]:
df.describe()

,Hours Studied,Previous Scores,Sleep Hours,Sample Question Papers Practiced,Performance Index
count,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000
mean,4.992900,69.445700,6.530600,4.583300,55.224800
std,2.589309,17.343152,1.695863,2.867348,19.212558
min,1.000000,40.000000,4.000000,0.000000,10.000000
25%,3.000000,54.000000,5.000000,2.000000,40.000000
50%,5.000000,69.000000,7.000000,5.000000,55.000000
75%,7.000000,85.000000,8.000000,7.000000,71.000000
max,9.000000,99.000000,9.000000,9.000000,100.000000

In [16]:
y = df['Performance Index'].copy()
X = df.drop(columns='Performance Index').copy()
X.head()

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced
0,7,99,Yes,9,1
1,4,82,No,4,2
2,8,51,Yes,7,2
3,5,52,Yes,5,2
4,7,75,No,8,5

In [17]:
X = p.get_dummies(X, columns=['Extracurricular Activities'])
X.head()

,Hours Studied,Previous Scores,Sleep Hours,Sample Question Papers Practiced,Extracurricular Activities_No,Extracurricular Activities_Yes
0,7,99,9,1,False,True
1,4,82,4,2,True,False
2,8,51,7,2,False,True
3,5,52,5,2,False,True
4,7,75,8,5,True,False

In [ ]:
#train-test split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2,
random_state=7)

In [ ]:
#Support Vector Regressor(SVR)
from sklearn.svm import SVR
svr = SVR()
svr.fit(X_train, y_train)
svr_prediction = svr.predict(X_test)
from sklearn.metrics import mean_absolute_error
svr_mae = mean_absolute_error(y_test, svr_prediction)
svr_mae # 1.8384445448641034

SyntaxError: invalid syntax (2458466271.py, line 1)

In [23]:
#Linear Regression
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr.fit(X_train, y_train)
lr_prediction = lr.predict(X_test)
lr_mae = mean_absolute_error(y_test, lr_prediction)
lr_mae # 1.6313121603176193

1.6313121603176202

In [22]:
#StandardScaler 
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
lr_pipeline = Pipeline([
('scaler', StandardScaler()),
('model', LinearRegression())
])
lr_pipeline.fit(X_train, y_train)
lr_pipeline_prediction = lr_pipeline.predict(X_test)
lr_pipeline_mae = mean_absolute_error(y_test, lr_pipeline_prediction)
lr_pipeline_mae #1.6313121603176188

1.631312160317619