


<div align="center">
  <h1>Apriori Algorithm For Market Basket
Analysis</h1>
</div>

In [ ]:
pip install mlxtend

In [ ]:
!pip install mlxtend

In [4]:
from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules
import pandas as pd

In [5]:
# Define the dataset
data = {
'Transaction ID': [1, 2, 3, 4, 5],
'Items': [['bread', 'milk'],
['bread', 'diaper', 'beer', 'eggs'],
['milk', 'diaper', 'beer', 'cola'],
['bread', 'milk', 'diaper', 'beer'],
['bread', 'milk', 'diaper', 'cola']]
}
# Convert the dataset into a pandas DataFrame
df = pd.DataFrame(data)
df

   Transaction ID                        Items
0               1                [bread, milk]
1               2  [bread, diaper, beer, eggs]
2               3   [milk, diaper, beer, cola]
3               4  [bread, milk, diaper, beer]
4               5  [bread, milk, diaper, cola]

In [6]:
# Convert the list of items in each transaction into a string
df['Items'] = df['Items'].apply(lambda x: ','.join(x))
df

   Transaction ID                   Items
0               1              bread,milk
1               2  bread,diaper,beer,eggs
2               3   milk,diaper,beer,cola
3               4  bread,milk,diaper,beer
4               5  bread,milk,diaper,cola

In [7]:
# Apply one-hot encoding to convert the transaction data into a binary
format
onehot = df['Items'].str.get_dummies(sep=',')
onehot

   beer  bread  cola  diaper  eggs  milk
0     0      1     0       0     0     1
1     1      1     0       1     1     0
2     1      0     1       1     0     1
3     1      1     0       1     0     1
4     0      1     1       1     0     1

In [8]:
# Apply the Apriori algorithm to find frequent itemsets
frequent_itemsets = apriori(onehot, min_support=0.4,
use_colnames=True)
frequent_itemsets

/Users/sushmamac/ml-in-30days/.venv/lib/python3.12/site-packages/mlxtend/frequent_patterns/fpcommon.py:161: DeprecationWarning: DataFrames with non-bool types result in worse computationalperformance and their support might be discontinued in the future.Please use a DataFrame with bool type
  warnings.warn(

    support               itemsets
0       0.6                 (beer)
1       0.8                (bread)
2       0.4                 (cola)
3       0.8               (diaper)
4       0.8                 (milk)
5       0.4          (beer, bread)
6       0.6         (beer, diaper)
7       0.4           (beer, milk)
8       0.6        (diaper, bread)
9       0.6          (bread, milk)
10      0.4         (diaper, cola)
11      0.4           (cola, milk)
12      0.6         (diaper, milk)
13      0.4  (beer, bread, diaper)
14      0.4   (beer, diaper, milk)
15      0.4  (diaper, bread, milk)
16      0.4   (diaper, cola, milk)

In [9]:
# Generate association rules
rules = association_rules(frequent_itemsets, metric='confidence',
min_threshold=0.7)
rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,representativity,leverage,conviction,zhangs_metric,jaccard,certainty,kulczynski
0,(beer),(diaper),0.6,0.8,0.6,1.00,1.250000,1.0,0.12,inf,0.500000,0.750000,1.000,0.875000
1,(diaper),(beer),0.8,0.6,0.6,0.75,1.250000,1.0,0.12,1.6,1.000000,0.750000,0.375,0.875000
2,(diaper),(bread),0.8,0.8,0.6,0.75,0.937500,1.0,-0.04,0.8,-0.250000,0.600000,-0.250,0.750000
3,(bread),(diaper),0.8,0.8,0.6,0.75,0.937500,1.0,-0.04,0.8,-0.250000,0.600000,-0.250,0.750000
4,(bread),(milk),0.8,0.8,0.6,0.75,0.937500,1.0,-0.04,0.8,-0.250000,0.600000,-0.250,0.750000
5,(milk),(bread),0.8,0.8,0.6,0.75,0.937500,1.0,-0.04,0.8,-0.250000,0.600000,-0.250,0.750000
6,(cola),(diaper),0.4,0.8,0.4,1.00,1.250000,1.0,0.08,inf,0.333333,0.500000,1.000,0.750000
7,(cola),(milk),0.4,0.8,0.4,1.00,1.250000,1.0,0.08,inf,0.333333,0.500000,1.000,0.750000
8,(diaper),(milk),0.8,0.8,0.6,0.75,0.937500,1.0,-0.04,0.8,-0.250000,0.600000,-0.250,0.750000
9,(milk),(diaper),0.8,0.8,0.6,0.75,0.937500,1.0,-0.04,0.8,-0.250000,0.600000,-0.250,0.750000
10,"(beer, bread)",(diaper),0.4,0.8,0.4,1.00,1.250000,1.0,0.08,inf,0.333333,0.500000,1.000,0.750000
11,"(beer, milk)",(diaper),0.4,0.8,0.4,1.00,1.250000,1.0,0.08,inf,0.333333,0.500000,1.000,0.750000
12,"(diaper, cola)",(milk),0.4,0.8,0.4,1.00,1.250000,1.0,0.08,inf,0.333333,0.500000,1.000,0.750000
13,"(cola, milk)",(diaper),0.4,0.8,0.4,1.00,1.250000,1.0,0.08,inf,0.333333,0.500000,1.000,0.750000
14,(cola),"(diaper, milk)",0.4,0.6,0.4,1.00,1.666667,1.0,0.16,inf,0.666667,0.666667,1.000,0.833333